---
title:
  - type: main
    text: Sétáló Budapest
  - type: subtitle
    text: Program - 2019
creator:
  - role: author
    text: Állampolgárok a centrumban Egyesület
  - role: editor
    text: Bodrog Zoltán
publisher:  Állampolgárok a centrumban Egyesület - Zaránd Péter
lang: hu
date: 2019
mainfont: DejaVu Sans
description: Puzsér Róbert programja a 2019-es budapesti önkormányzati választásokra
cover-image: ../assets/sbp-logo-w320.png
rights: All rights reserved
ibooks:
  version: 1.0
---
